/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:get_it/get_it.dart';
import 'package:pcassa/themes/app_colors.dart';

class CustomIcons {
  //CustomIcons();
  static final colorState = GetIt.I<AppColorobs>();
  static Image whitetable = Image(
    image: AssetImage('assets/icones/whitetable.png'),
    height: 40,
    width: 40,
    //color: colorState.isDark==false?AppColors.appBlack:AppColors.appWhite,
  );
  static const Image table = Image(
    image: AssetImage('assets/icones/table.png'),
    height: 40,
    width: 40,
  );
  static const Image search2 = Image(
    image: AssetImage('assets/icones/search2.png'),
    height: 40,
    width: 40,
  );
  static const Image group = Image(
    image: AssetImage('assets/icones/group.png'),
    height: 40,
    width: 40,
  );
  static const Image percent = Image(
    image: AssetImage('assets/icones/percent.png'),
    height: 40,
    width: 40,
  );
  static const Image closing = Image(
    image: AssetImage('assets/icones/closing.png'),
    height: 40,
    width: 40,
  );
  static const Image dop = Image(
    image: AssetImage('assets/icones/dop.png'),
    height: 40,
    width: 40,
  );
  static const Image plus = Image(
    image: AssetImage('assets/icones/plus.png'),
    height: 40,
    width: 40,
  );
  static const Image minus = Image(
    image: AssetImage('assets/icones/minus.png'),
    height: 40,
    width: 40,
  );
  static Image user = Image(
    image: AssetImage('assets/icones/user.png'),
    height: 40,
    width: 40,
  );
  static const Image left = Image(
    image: AssetImage('assets/icones/left.png'),
    height: 40,
    width: 40,
  );
  static const Image lock = Image(
    image: AssetImage('assets/icones/lock.png'),
    height: 40,
    width: 40,
  );
  static const Image home = Image(
    image: AssetImage('assets/icones/home.png'),
    height: 40,
    width: 40,
  );
  static const Image back = Image(
    image: AssetImage('assets/icones/back.png'),
    height: 40,
    width: 40,
  );
  static const Image bests = Image(
    image: AssetImage('assets/icones/bests.png'),
    height: 40,
    width: 40,
  );
  static const Image delete = Image(
    image: AssetImage('assets/icones/delete.png'),
    height: 40,
    width: 40,
  );
  static const Image discounts = Image(
    image: AssetImage('assets/icones/discounts.png'),
    height: 40,
    width: 40,
  );
  static const Image managermenu = Image(
    image: AssetImage('assets/icones/managermenu.png'),
    height: 60,
    width: 60,
  );
  static const Image minimize = Image(
    image: AssetImage('assets/icones/minimise.png'),
    height: 40,
    width: 40,
  );
  static const Image modifers = Image(
    image: AssetImage('assets/icones/modifers.png'),
    height: 40,
    width: 40,
  );
  static const Image out = Image(
    image: AssetImage('assets/icones/out.png'),
    height: 40,
    width: 40,
  );
  static const Image save = Image(
    image: AssetImage('assets/icones/save.png'),
    height: 40,
    width: 40,
  );
  static const Image search = Image(
    image: AssetImage('assets/icones/search.png'),
    height: 40,
    width: 40,
  );
  static const Image stop = Image(
    image: AssetImage('assets/icones/stop.png'),
    height: 40,
    width: 40,
  );
  static const Image check = Image(
    image: AssetImage('assets/icones/chek.png'),
    height: 40,
    width: 40,
  );
}
